# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('qr_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa_Evento_Assoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('presenca_confirmada', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_app.Evento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas_app.Pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='pessoa_evento',
            field=models.ManyToManyField(through='eventos_app.Pessoa_Evento_Assoc', to='pessoas_app.Pessoa'),
        ),
    ]
